[project]
name = "job-radar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "linus.anders.larsson@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
job-radar = "job_radar:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
